"""empty message

Revision ID: 06007d7c64a0
Revises: 87cc26a5c3da
Create Date: 2019-11-24 01:19:08.162441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06007d7c64a0'
down_revision = '87cc26a5c3da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('organizer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'organizer')
    # ### end Alembic commands ###
