"""empty message

Revision ID: 65923df8a192
Revises: fe831f1c1b30
Create Date: 2019-11-24 00:35:40.297718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65923df8a192'
down_revision = 'fe831f1c1b30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('location', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'location')
    # ### end Alembic commands ###
