"""empty message

Revision ID: 87cc26a5c3da
Revises: daee137aa648
Create Date: 2019-11-24 00:56:16.175352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87cc26a5c3da'
down_revision = 'daee137aa648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'time')
    # ### end Alembic commands ###
