"""empty message

Revision ID: 953ef4e6c5a3
Revises: 65923df8a192
Create Date: 2019-11-24 00:55:18.398132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '953ef4e6c5a3'
down_revision = '65923df8a192'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'date')
    # ### end Alembic commands ###
