"""empty message

Revision ID: fc989ae45dd1
Revises: 
Create Date: 2019-11-23 16:50:23.209869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc989ae45dd1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_url', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
