"""empty message

Revision ID: fe831f1c1b30
Revises: 4713c8101f2d
Create Date: 2019-11-24 00:35:17.958428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe831f1c1b30'
down_revision = '4713c8101f2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('venue_name', sa.String(length=20), nullable=False))
    op.drop_column('event', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('location', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('event', 'venue_name')
    # ### end Alembic commands ###
